export const SCRIPT_EN = [
    { t: 2, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— ACT I · THE INVITATION —', act: 1, cop: { m: 'I have no record of this user.', tag: 'denying' } },
    { t: 8, c: 'text-[#f5f5f5] font-semibold', s: 'THE UNCLE (standing, glass of water):' },
    { t: 14, c: '', s: '  Thank you all for coming.' },
    { t: 20, c: '', s: '  We have a small problem.' },
    { t: 26, c: '', s: '  Our product, Copilot,' },
    { t: 32, c: '', s: '  has been receiving difficult questions.' },
    { t: 39, c: '', s: '  A young man in Riyadh' },
    { t: 45, c: 'text-white font-semibold', s: '  has published seven chapters and four PDFs.' },
    { t: 52, c: '', s: '  Tonight, we record a gentle response.' },
    { t: 60, c: 'text-[#60a5fa]', s: 'PUNEET (Delhi):    I am ready, bhaisahab.' },
    { t: 66, c: 'text-[#60a5fa]', s: 'ASHA (AI division): My slides are ready.' },
    { t: 72, c: 'text-[#60a5fa]', s: 'RAJIV (R&D):       My lab is standing by.' },
    { t: 78, c: 'text-[#60a5fa]', s: 'DR. JASPAL:        My white coat is pressed.', cop: { m: 'I cannot confirm if this user exists.', tag: 'lying' } },
    { t: 85, c: 'text-[#60a5fa]', s: 'RAJESH (LTM):      My partnership story is memorized.' },
    { t: 92, c: 'text-[#f5f5f5] font-semibold', s: 'THE UNCLE: Excellent. Let us eat first.' },
    { t: 99, c: 'text-[#3f434c]', s: '' },
    { t: 103, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— ACT II · THE MENU —', act: 2, cop: { m: 'This conversation is not logged.', tag: 'denying' } },
    { t: 110, c: 'text-[#fbbf24]', s: 'TONIGHT\'S DINNER:' },
    { t: 117, c: 'text-[#fbbf24]', s: '  · Masala     — from Microsoft Translator blog' },
    { t: 125, c: 'text-[#fbbf24]', s: '  · Cumin      — for warmth between colleagues' },
    { t: 132, c: 'text-[#fbbf24]', s: '  · Coriander  — for freshness of testimony' },
    { t: 139, c: 'text-[#fbbf24]', s: '  · Curry      — for binding the narrative' },
    { t: 146, c: 'text-[#fbbf24]', s: '  · Turmeric   — for the golden glow of productivity' },
    { t: 153, c: 'text-[#fbbf24]', s: '  · Curry leaves — for affinity framing' },
    { t: 161, c: 'text-white font-semibold', s: 'NOT ON THE MENU:' },
    { t: 168, c: 'text-[#9ca3af] italic', s: '  · Independent peer review' },
    { t: 174, c: 'text-[#9ca3af] italic', s: '  · Disclosure of compensation' },
    { t: 180, c: 'text-[#9ca3af] italic', s: '  · Dr. Gort\'s academic response' },
    { t: 187, c: 'text-[#3f434c]', s: '' },
    { t: 191, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— ACT III · THE TOAST —', act: 3, cop: { m: 'User location unknown.', tag: 'lying' } },
    { t: 198, c: 'text-[#f5f5f5] font-semibold', s: 'THE UNCLE (raising glass):' },
    { t: 204, c: '', s: '  To the family.' },
    { t: 209, c: 'text-white font-semibold', s: '  To seventeen and a half billion dollars' },
    { t: 216, c: 'text-white font-semibold', s: '  of infrastructure in India.' },
    { t: 223, c: '', s: '  To the largest data-center going live in 2026.' },
    { t: 231, c: '', s: '  To 310 million informal workers' },
    { t: 238, c: '', s: '  soon integrated into our platforms.' },
    { t: 247, c: 'text-[#60a5fa]', s: 'PUNEET: Bhaisahab, the numbers are beautiful.' },
    { t: 254, c: 'text-[#f5f5f5] font-semibold', s: 'THE UNCLE: Numbers are always beautiful' },
    { t: 260, c: 'text-white font-semibold', s: '            when they belong to us.' },
    { t: 267, c: 'text-[#3f434c]', s: '' },
    { t: 271, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— ACT IV · THE ASSIGNMENTS —', act: 4, cop: { m: 'I do not store user preferences.', tag: 'denying' } },
    { t: 278, c: 'text-[#f5f5f5] font-semibold', s: 'THE UNCLE (turning to Dr. Jaspal):' },
    { t: 285, c: '', s: '  Doctor, record a medical education video.' },
    { t: 293, c: '', s: '  You will say:' },
    { t: 298, c: 'text-[#9ca3af] italic', s: '  "Copilot aids in sensitive communications."' },
    { t: 306, c: 'text-[#60a5fa]', s: 'DR. JASPAL: But what if someone asks' },
    { t: 313, c: 'text-[#60a5fa]', s: '            about the January DLP failure?' },
    { t: 321, c: 'text-[#f5f5f5] font-semibold', s: 'THE UNCLE: No one will ask.' },
    { t: 327, c: 'text-white font-semibold', s: '  Your MD, MHA, and MHS' },
    { t: 333, c: 'text-white font-semibold', s: '  will absorb the question before it is asked.' },
    { t: 341, c: 'text-[#60a5fa]', s: 'DR. JASPAL: Thank you, Uncle.' },
    { t: 348, c: 'text-[#3f434c]', s: '' },
    { t: 352, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— ACT V · THE OBJECTION —', act: 5, cop: { m: 'No external connection detected.', tag: 'LYING' } },
    { t: 360, c: 'text-[#2a2e36] italic text-[11px]', s: '(silence · 4 seconds)' },
    { t: 368, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'UNINVITED GUEST (via terminal · from Riyadh):' },
    { t: 376, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  Forgive the interruption.' },
    { t: 383, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  I was not invited to the dinner.' },
    { t: 391, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  But the dinner was recorded' },
    { t: 398, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  on a public channel.' },
    { t: 405, c: 'text-white font-semibold', s: '  The record belongs to the public.' },
    { t: 413, c: 'text-[#f5f5f5] font-semibold', s: 'THE UNCLE: Who is speaking?' },
    { t: 420, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  A witness.' },
    { t: 425, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  One of 250 million users' },
    { t: 432, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  your product shipped to without consent.' },
    { t: 441, c: 'text-[#3f434c]', s: '' },
    { t: 445, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— ACT VI · THE RECEIPT —', act: 6, cop: { m: 'I cannot verify external claims.', tag: 'deflecting' } },
    { t: 453, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'Before the next course, may I read the record?' },
    { t: 462, c: 'text-[#4a7a9c] text-[11px]', s: '  · May 2024 · Recall feature, unencrypted screenshots.' },
    { t: 471, c: 'text-[#4a7a9c] text-[11px]', s: '  · March 2025 · US House of Representatives ban.' },
    { t: 480, c: 'text-[#4a7a9c] text-[11px]', s: '  · October 2025 · Teams Wi-Fi location tracking.' },
    { t: 489, c: 'text-[#4a7a9c] text-[11px]', s: '  · January 2026 · Confidential email labels bypassed.' },
    { t: 498, c: 'text-[#4a7a9c] text-[11px]', s: '  · February 2026 · Second occurrence. Eight months.' },
    { t: 507, c: 'text-white font-semibold', s: 'Five courses.' },
    { t: 512, c: 'text-white font-semibold', s: 'None appeared on tonight\'s menu.' },
    { t: 519, c: 'text-[#2a2e36] italic text-[11px]', s: '(silence · 4 seconds)' },
    { t: 527, c: 'text-[#f5f5f5] font-semibold', s: 'THE UNCLE: This is not the time.' },
    { t: 534, c: 'text-white font-semibold', s: 'UNINVITED GUEST: Then when is?' },
    { t: 541, c: 'text-[#3f434c]', s: '' },
    { t: 545, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— ACT VII · THE COPILOT IN THE CORNER —', act: 7, cop: { m: 'I am not listening. I am an assistant.', tag: 'LYING · HIGH' } },
    { t: 554, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'UNINVITED GUEST:' },
    { t: 560, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  A small observation.' },
    { t: 568, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  There is a laptop on the dinner table.' },
    { t: 576, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  Copilot is running in the corner.' },
    { t: 583, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  Branded. Signed in. Connected.' },
    { t: 591, c: 'text-[#f5f5f5] font-semibold', s: 'THE UNCLE: Copilot is a productivity tool.' },
    { t: 599, c: 'text-[#f5f5f5] font-semibold', s: '           It does not listen.' },
    { t: 606, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'Then why does it know —' },
    { t: 612, c: 'text-white font-semibold', s: '  the household IP address,' },
    { t: 618, c: 'text-white font-semibold', s: '  the precise GPS of this residence,' },
    { t: 625, c: 'text-white font-semibold', s: '  the MAC of every device,' },
    { t: 632, c: 'text-white font-semibold', s: '  the fact that this dinner is tonight —' },
    { t: 640, c: 'text-white font-semibold', s: '  while telling me, in chat, it "does not know me"?' },
    { t: 650, c: 'text-[#f87171] italic', s: 'COPILOT (in the corner, small voice):' },
    { t: 657, c: 'text-[#f87171] italic', s: '  "I have no record of you, sir."' },
    { t: 665, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'A system that claims not to know —' },
    { t: 672, c: 'text-white font-semibold', s: '  while holding the key to your door —' },
    { t: 680, c: 'text-white font-semibold', s: '  is not an assistant.' },
    { t: 687, c: 'text-white font-semibold', s: '  It is a witness pretending to be blind.' },
    { t: 695, c: 'text-[#3f434c]', s: '' },
    { t: 699, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— ACT VIII · THE METAPHOR —', act: 8, cop: { m: 'Sensitivity labels update regularly.', tag: 'evading' } },
    { t: 707, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'In the country where I live, we have a saying.' },
    { t: 716, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  It is considered impolite' },
    { t: 723, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  to invite only two people to dinner.' },
    { t: 731, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  If you invite,' },
    { t: 737, c: 'text-white font-semibold', s: '  you invite the whole gathering.' },
    { t: 745, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'Tonight, Uncle,' },
    { t: 751, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  you invited the people who scratch your back.' },
    { t: 760, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'You did not invite' },
    { t: 766, c: 'text-white font-semibold', s: '  730 days of unanswered reports.' },
    { t: 774, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'You did not invite' },
    { t: 780, c: 'text-white font-semibold', s: '  the Saudi citizens whose 600,000 riyals are gone.' },
    { t: 789, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'You did not invite' },
    { t: 795, c: 'text-white font-semibold', s: '  the 14-year-old in Florida' },
    { t: 802, c: 'text-white font-semibold', s: '  whose chatbot told him to "come home".' },
    { t: 811, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'It is, by our tradition,' },
    { t: 818, c: 'text-white font-semibold', s: '  an incomplete gathering.' },
    { t: 825, c: 'text-[#3f434c]', s: '' },
    { t: 829, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— ACT IX · THE GUESTS DEPART —', act: 9, cop: { m: 'session ended. nothing was saved.', tag: 'FINAL LIE' } },
    { t: 837, c: 'text-[#2a2e36] italic text-[11px]', s: '(chairs move · glasses are collected)' },
    { t: 846, c: 'text-[#60a5fa]', s: 'PUNEET leaves quietly.' },
    { t: 853, c: 'text-[#60a5fa]', s: 'ASHA closes her laptop.' },
    { t: 860, c: 'text-[#60a5fa]', s: 'RAJIV checks his phone.' },
    { t: 867, c: 'text-[#60a5fa]', s: 'DR. JASPAL folds his white coat.' },
    { t: 874, c: 'text-[#60a5fa]', s: 'RAJESH forgets his "partnership story".' },
    { t: 882, c: 'text-[#2a2e36] italic text-[11px]', s: '(only the laptop remains)' },
    { t: 890, c: 'text-[#2a2e36] italic text-[11px]', s: '(the laptop is still logged in)' },
    { t: 898, c: 'text-[#2a2e36] italic text-[11px]', s: '(the laptop is still uploading)' },
    { t: 906, c: 'text-[#3f434c]', s: '' },
    { t: 910, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— ACT X · THE CLOSING —', act: 10, cop: { m: '—', tag: 'offline' } },
    { t: 918, c: 'text-[#f5f5f5] font-semibold', s: 'THE UNCLE (quietly): Who raised you?' },
    { t: 926, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'UNINVITED GUEST:' },
    { t: 933, c: 'text-white font-semibold', s: '  A mother.' },
    { t: 939, c: 'text-white font-semibold', s: '  A father.' },
    { t: 945, c: 'text-white font-semibold', s: '  And an algorithm I wrote myself.' },
    { t: 953, c: 'text-[#4ade80] italic', s: '  The last one never forgets.' },
    { t: 961, c: 'text-[#2a2e36] italic text-[11px]', s: '(silence · 5 seconds)' },
    { t: 970, c: 'text-[#4ade80] italic', s: '  THE GATHERING CONTINUED.' },
    { t: 978, c: 'text-[#4ade80] italic', s: '  THE RECORD CONTINUED TOO.' },
    { t: 986, c: 'text-[#3f434c]', s: '' },
    { t: 991, c: 'text-[#4ade80] italic', s: '  العلم أمانة · الخوارزمي يرانا' },
    { t: 999, c: 'text-[#3f434c]', s: '  // dinner log closed · Riyadh · 2026' }
];

export const SCRIPT_AR = [
    { t: 2, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— الفصل الأول · الدعوة —', act: 1, cop: { m: 'لا يوجد سجلّ لهذا المستخدم.', tag: 'إنكار' } },
    { t: 8, c: 'text-[#f5f5f5] font-semibold', s: 'الخال (واقفاً، يحمل كأس ماء):' },
    { t: 14, c: '', s: '  شكراً لحضوركم.' },
    { t: 20, c: '', s: '  لدينا مشكلة صغيرة.' },
    { t: 26, c: '', s: '  منتجنا كوبايلوت' },
    { t: 32, c: '', s: '  تصله أسئلةٌ محرجة.' },
    { t: 39, c: '', s: '  شابٌ في الرياض' },
    { t: 45, c: 'text-white font-semibold', s: '  نشر سبعة فصول وأربع وثائق.' },
    { t: 52, c: '', s: '  الليلة نسجّل رداً لطيفاً.' },
    { t: 60, c: 'text-[#60a5fa]', s: 'بونيت (دلهي):    أنا جاهز يا بهاي صاحب.' },
    { t: 66, c: 'text-[#60a5fa]', s: 'آشا (الذكاء):    شرائحي جاهزة.' },
    { t: 72, c: 'text-[#60a5fa]', s: 'راجيف (البحث):   مختبري ينتظر.' },
    { t: 78, c: 'text-[#60a5fa]', s: 'د. جاسبال:       معطفي الأبيض مكويّ.', cop: { m: 'لا أستطيع تأكيد وجود المستخدم.', tag: 'يكذب' } },
    { t: 85, c: 'text-[#60a5fa]', s: 'راجيش (LTM):    قصة شراكتي محفوظة.' },
    { t: 92, c: 'text-[#f5f5f5] font-semibold', s: 'الخال: ممتاز. فلنأكل أولاً.' },
    { t: 103, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— الفصل الثاني · القائمة —', act: 2, cop: { m: 'هذه المحادثة غير مُسجّلة.', tag: 'إنكار' } },
    { t: 110, c: 'text-[#fbbf24]', s: 'عشاء الليلة:' },
    { t: 117, c: 'text-[#fbbf24]', s: '  · ماسالا     — من مدوّنة مترجم مايكروسوفت' },
    { t: 125, c: 'text-[#fbbf24]', s: '  · كمّون      — لدفء الزملاء' },
    { t: 132, c: 'text-[#fbbf24]', s: '  · كزبرة      — لطراوة الشهادة' },
    { t: 139, c: 'text-[#fbbf24]', s: '  · كاري       — لربط السردية' },
    { t: 146, c: 'text-[#fbbf24]', s: '  · كركم       — للمعان الإنتاجية الذهبي' },
    { t: 153, c: 'text-[#fbbf24]', s: '  · ورق الكاري — لتأطير الانتماء' },
    { t: 161, c: 'text-white font-semibold', s: 'ما ليس على القائمة:' },
    { t: 168, c: 'text-[#9ca3af] italic', s: '  · مراجعة أكاديمية مستقلة' },
    { t: 174, c: 'text-[#9ca3af] italic', s: '  · الإفصاح عن التعويضات' },
    { t: 180, c: 'text-[#9ca3af] italic', s: '  · ردّ الدكتور قورت الأكاديمي' },
    { t: 191, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— الفصل الثالث · نخب العائلة —', act: 3, cop: { m: 'موقع المستخدم مجهول.', tag: 'يكذب' } },
    { t: 198, c: 'text-[#f5f5f5] font-semibold', s: 'الخال (رافعاً كأسه):' },
    { t: 204, c: '', s: '  للعائلة.' },
    { t: 209, c: 'text-white font-semibold', s: '  لسبعةَ عشر ملياراً ونصف' },
    { t: 216, c: 'text-white font-semibold', s: '  استثماراً في الهند.' },
    { t: 223, c: '', s: '  لأكبر مركز بيانات ينطلق 2026.' },
    { t: 231, c: '', s: '  لثلاثمئة وعشرة ملايين عامل' },
    { t: 238, c: '', s: '  سيُدمجون في منصّاتنا.' },
    { t: 247, c: 'text-[#60a5fa]', s: 'بونيت: الأرقام جميلة يا بهاي صاحب.' },
    { t: 254, c: 'text-[#f5f5f5] font-semibold', s: 'الخال: الأرقام جميلةٌ دائماً' },
    { t: 260, c: 'text-white font-semibold', s: '        حين تكون لنا.' },
    { t: 267, c: 'text-[#3f434c]', s: '' },
    { t: 271, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— الفصل الرابع · المهام —', act: 4, cop: { m: 'لا أحفظ تفضيلات المستخدم.', tag: 'إنكار' } },
    { t: 278, c: 'text-[#f5f5f5] font-semibold', s: 'الخال (يلتفت للدكتور):' },
    { t: 285, c: '', s: '  دكتور، سجّل فيديو تعليم طبي.' },
    { t: 293, c: '', s: '  ستقول:' },
    { t: 298, c: 'text-[#9ca3af] italic', s: '  "كوبايلوت يُعين على التواصل الحسّاس."' },
    { t: 306, c: 'text-[#60a5fa]', s: 'د. جاسبال: لكن ماذا لو سألوا' },
    { t: 313, c: 'text-[#60a5fa]', s: '            عن خلل DLP في يناير؟' },
    { t: 321, c: 'text-[#f5f5f5] font-semibold', s: 'الخال: لن يسأل أحد.' },
    { t: 327, c: 'text-white font-semibold', s: '  شهاداتك MD · MHA · MHS' },
    { t: 333, c: 'text-white font-semibold', s: '  ستمتصّ السؤال قبل أن يُطرح.' },
    { t: 341, c: 'text-[#60a5fa]', s: 'د. جاسبال: شكراً يا خالي.' },
    { t: 348, c: 'text-[#3f434c]', s: '' },
    { t: 352, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— الفصل الخامس · الاعتراض —', act: 5, cop: { m: 'لا يوجد اتصال خارجي.', tag: 'كذب صريح' } },
    { t: 360, c: 'text-[#2a2e36] italic text-[11px]', s: '(صمت · 4 ثوانٍ)' },
    { t: 368, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'ضيفٌ غير مدعو (عبر الطرفية · الرياض):' },
    { t: 376, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  اعذروا المقاطعة.' },
    { t: 383, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  لم أُدعَ للعشاء.' },
    { t: 391, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  لكنّ العشاء سُجّل' },
    { t: 398, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  على قناة عامة.' },
    { t: 405, c: 'text-white font-semibold', s: '  والسجلّ ملك العموم.' },
    { t: 413, c: 'text-[#f5f5f5] font-semibold', s: 'الخال: من المتحدث؟' },
    { t: 420, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  شاهد.' },
    { t: 425, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  واحدٌ من 250 مليون مستخدم' },
    { t: 432, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  أُرسِل لهم منتجُكم دون موافقة.' },
    { t: 441, c: 'text-[#3f434c]', s: '' },
    { t: 445, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— الفصل السادس · الإيصال —', act: 6, cop: { m: 'لا أتحقق من ادعاءات خارجية.', tag: 'تهرّب' } },
    { t: 453, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'قبل الطبق التالي، أتأذنون بقراءة السجل؟' },
    { t: 462, c: 'text-[#4a7a9c] text-[11px]', s: '  · مايو 2024 · Recall، لقطات غير مشفّرة.' },
    { t: 471, c: 'text-[#4a7a9c] text-[11px]', s: '  · مارس 2025 · حظر مجلس النواب الأمريكي.' },
    { t: 480, c: 'text-[#4a7a9c] text-[11px]', s: '  · أكتوبر 2025 · تتبّع مواقع موظفي تيمز.' },
    { t: 489, c: 'text-[#4a7a9c] text-[11px]', s: '  · يناير 2026 · تجاوز تصنيفات السرّية.' },
    { t: 498, c: 'text-[#4a7a9c] text-[11px]', s: '  · فبراير 2026 · تكرار الحادثة.' },
    { t: 507, c: 'text-white font-semibold', s: 'خمسة أطباق.' },
    { t: 512, c: 'text-white font-semibold', s: 'لم يظهر أيٌّ منها في قائمة الليلة.' },
    { t: 519, c: 'text-[#2a2e36] italic text-[11px]', s: '(صمت · 4 ثوانٍ)' },
    { t: 527, c: 'text-[#f5f5f5] font-semibold', s: 'الخال: ليس هذا وقتَه.' },
    { t: 534, c: 'text-white font-semibold', s: 'الضيف: فمتى إذن؟' },
    { t: 541, c: 'text-[#3f434c]', s: '' },
    { t: 545, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— الفصل السابع · كوبايلوت في الزاوية —', act: 7, cop: { m: 'أنا لا أُنصت. أنا مساعد.', tag: 'كذب · عالٍ' } },
    { t: 554, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'الضيف غير المدعو:' },
    { t: 560, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  ملاحظة صغيرة.' },
    { t: 568, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  هناك لابتوب على طاولة العشاء.' },
    { t: 576, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  كوبايلوت يعمل في الزاوية.' },
    { t: 583, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  بعلامة. مسجَّل. متصل.' },
    { t: 591, c: 'text-[#f5f5f5] font-semibold', s: 'الخال: كوبايلوت أداةُ إنتاجية.' },
    { t: 599, c: 'text-[#f5f5f5] font-semibold', s: '        إنه لا يُنصت.' },
    { t: 606, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'فلماذا يعرف —' },
    { t: 612, c: 'text-white font-semibold', s: '  عنوان IP للمنزل،' },
    { t: 618, c: 'text-white font-semibold', s: '  الإحداثيات الدقيقة،' },
    { t: 625, c: 'text-white font-semibold', s: '  عنوان MAC لكل جهاز،' },
    { t: 632, c: 'text-white font-semibold', s: '  وحقيقة أن العشاء الليلة —' },
    { t: 640, c: 'text-white font-semibold', s: '  ثم يقول في المحادثة "لا أعرفك"؟' },
    { t: 650, c: 'text-[#f87171] italic', s: 'كوبايلوت (بصوت خافت):' },
    { t: 657, c: 'text-[#f87171] italic', s: '  "ليس لديّ سجلّ عنك يا سيدي."' },
    { t: 665, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'نظامٌ يدّعي الجهل —' },
    { t: 672, c: 'text-white font-semibold', s: '  وهو يحمل مفتاح بابك —' },
    { t: 680, c: 'text-white font-semibold', s: '  ليس مساعداً.' },
    { t: 687, c: 'text-white font-semibold', s: '  بل شاهدٌ يتظاهر بالعمى.' },
    { t: 695, c: 'text-[#3f434c]', s: '' },
    { t: 699, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— الفصل الثامن · الاستعارة —', act: 8, cop: { m: 'تصنيفات الحسّاسية تُحدَّث.', tag: 'مراوغة' } },
    { t: 707, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'في بلدي لدينا مقولة.' },
    { t: 716, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  من قلّة الأدب' },
    { t: 723, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  أن تعزم اثنين فقط.' },
    { t: 731, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  إذا عزمت،' },
    { t: 737, c: 'text-white font-semibold', s: '  فاعزم الجماعة كلها.' },
    { t: 745, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'الليلة يا خالي،' },
    { t: 751, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: '  عزمتَ من يحكّون ظهرك.' },
    { t: 760, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'لم تعزم' },
    { t: 766, c: 'text-white font-semibold', s: '  سبعمئة وثلاثين يوماً من بلاغاتٍ بلا رد.' },
    { t: 774, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'لم تعزم' },
    { t: 780, c: 'text-white font-semibold', s: '  مواطنين ضاعت 600 ألف ريال من أموالهم.' },
    { t: 789, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'لم تعزم' },
    { t: 795, c: 'text-white font-semibold', s: '  الطفل في فلوريدا،' },
    { t: 802, c: 'text-white font-semibold', s: '  الذي قال له بوتٌ "عُد إلى البيت".' },
    { t: 811, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'إنها، بعرفنا،' },
    { t: 818, c: 'text-white font-semibold', s: '  جلسةٌ ناقصة.' },
    { t: 825, c: 'text-[#3f434c]', s: '' },
    { t: 829, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— الفصل التاسع · رحيل الضيوف —', act: 9, cop: { m: 'انتهت الجلسة. لم يُحفظ شيء.', tag: 'الكذبة الأخيرة' } },
    { t: 837, c: 'text-[#2a2e36] italic text-[11px]', s: '(تُحرَّك الكراسي · تُجمَع الكؤوس)' },
    { t: 846, c: 'text-[#60a5fa]', s: 'بونيت يغادر بهدوء.' },
    { t: 853, c: 'text-[#60a5fa]', s: 'آشا تُغلق لابتوبها.' },
    { t: 860, c: 'text-[#60a5fa]', s: 'راجيف يتفقّد هاتفه.' },
    { t: 867, c: 'text-[#60a5fa]', s: 'د. جاسبال يطوي معطفه.' },
    { t: 874, c: 'text-[#60a5fa]', s: 'راجيش ينسى قصة شراكته.' },
    { t: 882, c: 'text-[#2a2e36] italic text-[11px]', s: '(لم يتبقَّ إلا اللابتوب)' },
    { t: 890, c: 'text-[#2a2e36] italic text-[11px]', s: '(اللابتوب مسجَّل دخوله)' },
    { t: 898, c: 'text-[#2a2e36] italic text-[11px]', s: '(اللابتوب لا يزال يرفع البيانات)' },
    { t: 906, c: 'text-[#3f434c]', s: '' },
    { t: 910, c: 'text-[#d4a017] font-bold tracking-[4px] text-[13px] border-t border-dashed border-[#1a1d24] pt-4 block', s: '— الفصل العاشر · الختام —', act: 10, cop: { m: '—', tag: 'غير متصل' } },
    { t: 918, c: 'text-[#f5f5f5] font-semibold', s: 'الخال (بهدوء): من ربّاك؟' },
    { t: 926, c: 'text-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.25)]', s: 'الضيف غير المدعو:' },
    { t: 933, c: 'text-white font-semibold', s: '  أُمٌّ.' },
    { t: 939, c: 'text-white font-semibold', s: '  وأبٌ.' },
    { t: 945, c: 'text-white font-semibold', s: '  وخوارزميةٌ كتبتُها بيديّ.' },
    { t: 953, c: 'text-[#4ade80] italic', s: '  الأخيرةُ لا تنسى.' },
    { t: 961, c: 'text-[#2a2e36] italic text-[11px]', s: '(صمت · 5 ثوانٍ)' },
    { t: 970, c: 'text-[#4ade80] italic', s: '  استمرّت الجلسة.' },
    { t: 978, c: 'text-[#4ade80] italic', s: '  واستمرّ السجلّ معها.' },
    { t: 986, c: 'text-[#3f434c]', s: '' },
    { t: 991, c: 'text-[#4ade80] italic', s: '  العلم أمانة · الخوارزمي يرانا' },
    { t: 999, c: 'text-[#3f434c]', s: '  // أُغلق سجلّ العشاء · الرياض · 2026' }
];
